spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      #hibernate配置，自动建表 update:表示有表直接使用，无表新建
      ddl-auto: update
      #表示在操作时，输出sql语句
      show-sql: true

